import { Property } from '@/api/types/property.type'

export interface ListingsCounts {
  all: number
  expired: number
  expiring: number
  active: number
  pending: number
  review: number
  payment: number
  rejected: number
  archived: number
}

export const MOCK_LISTINGS: Property[] = [
  // VIP Diamond - Expired
  {
    id: '41341840',
    code: '41341840',
    title:
      'Cho thuê văn phòng đơn nguyên B tầng trung của tòa nhà 9 tầng cao cấp, gần quận ủy Hoàng Mai',
    description: 'Văn phòng đơn nguyên tại tòa nhà cao cấp',
    address: 'Hoàng Mai, Hà Nội',
    city: 'Hà Nội',
    property_type: 'Cho thuê văn phòng',
    bedrooms: 0,
    bathrooms: 0,
    price: 50000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 150,
    verified: true,
    package_type: 'vip_diamond',
    status: 'expired',
    posted_date: '2024-11-27',
    expiry_date: '2024-12-12',
    auto_repost: false,
    stats: {
      views: 505,
      contacts: 45,
      customers: 62,
    },
  },
  // Standard - Active with rank
  {
    id: '41934454',
    code: '41934454',
    title: 'Cho thuê CC mini Quan Nhân, 8,5 triệu, 50m2, đẹp, đầy đủ tiện ích',
    description: 'Chung cư mini tại Quan Nhân',
    address: 'Thanh Xuân, Hà Nội',
    city: 'Hà Nội',
    property_type: 'Cho thuê chung cư mini, căn hộ dịch vụ',
    bedrooms: 1,
    bathrooms: 1,
    price: 8500000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 50,
    verified: true,
    package_type: 'standard',
    status: 'active',
    posted_date: '2024-12-26',
    expiry_date: '2025-01-26',
    auto_repost: true,
    rank: {
      page: 1,
      position: 3,
    },
    stats: {
      views: 342,
      contacts: 18,
      customers: 7,
    },
  },
  // VIP Gold - Pending
  {
    id: '41934455',
    code: '41934455',
    title: 'Cho thuê căn hộ Royal City, 3PN, view đẹp, full nội thất',
    description: 'Căn hộ cao cấp tại Royal City',
    address: 'Thanh Xuân, Hà Nội',
    city: 'Hà Nội',
    property_type: 'Cho thuê căn hộ chung cư',
    bedrooms: 3,
    bathrooms: 2,
    price: 18000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 110,
    verified: true,
    package_type: 'vip_gold',
    status: 'pending',
    posted_date: '2024-12-28',
    expiry_date: '2025-01-28',
    auto_repost: false,
    stats: {
      views: 89,
      contacts: 5,
      customers: 2,
    },
  },
  // VIP Silver - Active, no rank, high stats
  {
    id: '41934456',
    code: '41934456',
    title: 'Cho thuê nhà mặt phố Hoàn Kiếm, vị trí đắc địa',
    description: 'Nhà mặt phố tại trung tâm Hà Nội',
    address: 'Hoàn Kiếm, Hà Nội',
    city: 'Hà Nội',
    property_type: 'Cho thuê nhà mặt phố',
    bedrooms: 4,
    bathrooms: 3,
    price: 75000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 200,
    verified: true,
    package_type: 'vip_silver',
    status: 'active',
    posted_date: '2024-12-24',
    expiry_date: '2025-01-24',
    auto_repost: true,
    stats: {
      views: 1580,
      contacts: 124,
      customers: 35,
    },
  },
  // Basic - Review status
  {
    id: '41934457',
    code: '41934457',
    title: 'Cho thuê phòng trọ sinh viên gần Đại học Quốc gia',
    description: 'Phòng trọ cho sinh viên',
    address: 'Cầu Giấy, Hà Nội',
    city: 'Hà Nội',
    property_type: 'Cho thuê phòng trọ',
    bedrooms: 1,
    bathrooms: 1,
    price: 4200000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 25,
    verified: false,
    package_type: 'basic',
    status: 'review',
    posted_date: '2024-12-30',
    expiry_date: '2025-01-30',
    auto_repost: false,
    stats: {
      views: 0,
      contacts: 0,
      customers: 0,
    },
  },
  // VIP Diamond - Active with high rank
  {
    id: '41934458',
    code: '41934458',
    title: 'Cho thuê biệt thự Vinhomes Riverside, 5PN, sân vườn rộng',
    description: 'Biệt thự cao cấp tại Vinhomes Riverside',
    address: 'Long Biên, Hà Nội',
    city: 'Hà Nội',
    property_type: 'Cho thuê biệt thự',
    bedrooms: 5,
    bathrooms: 4,
    price: 80000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 300,
    verified: true,
    package_type: 'vip_diamond',
    status: 'active',
    posted_date: '2024-12-15',
    expiry_date: '2025-01-15',
    auto_repost: true,
    rank: {
      page: 1,
      position: 1,
    },
    stats: {
      views: 2100,
      contacts: 156,
      customers: 28,
    },
  },
  // Standard - Rejected
  {
    id: '41934459',
    code: '41934459',
    title: 'Cho thuê căn hộ dịch vụ Cầu Giấy, studio, giá tốt',
    description: 'Căn hộ dịch vụ tại Cầu Giấy',
    address: 'Cầu Giấy, Hà Nội',
    city: 'Hà Nội',
    property_type: 'Cho thuê căn hộ dịch vụ',
    bedrooms: 0,
    bathrooms: 1,
    price: 7000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 30,
    verified: false,
    package_type: 'standard',
    status: 'rejected',
    posted_date: '2024-12-25',
    expiry_date: '2025-01-25',
    auto_repost: false,
    stats: {
      views: 12,
      contacts: 1,
      customers: 0,
    },
  },
  // VIP Gold - Payment pending
  {
    id: '41934460',
    code: '41934460',
    title: 'Cho thuê shop house mặt phố Trần Duy Hưng, kinh doanh tốt',
    description: 'Shop house mặt phố kinh doanh',
    address: 'Cầu Giấy, Hà Nội',
    city: 'Hà Nội',
    property_type: 'Cho thuê mặt bằng',
    bedrooms: 0,
    bathrooms: 2,
    price: 120000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 200,
    verified: true,
    package_type: 'vip_gold',
    status: 'payment',
    posted_date: '2024-12-29',
    expiry_date: '2025-01-29',
    auto_repost: false,
    stats: {
      views: 0,
      contacts: 0,
      customers: 0,
    },
  },
  // VIP Silver - Expiring
  {
    id: '41934461',
    code: '41934461',
    title: 'Cho thuê nhà riêng 3 tầng tại Cầu Giấy',
    description: 'Nhà riêng 3 tầng, vị trí đẹp',
    address: 'Cầu Giấy, Hà Nội',
    city: 'Hà Nội',
    property_type: 'Cho thuê nhà riêng',
    bedrooms: 4,
    bathrooms: 3,
    price: 35000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 120,
    verified: true,
    package_type: 'vip_silver',
    status: 'expiring',
    posted_date: '2024-11-20',
    expiry_date: '2025-01-02',
    auto_repost: true,
    stats: {
      views: 1250,
      contacts: 89,
      customers: 15,
    },
  },
  // Standard - Archived
  {
    id: '41934462',
    code: '41934462',
    title: 'Cho thuê shophouse tại Times City, mặt tiền đẹp',
    description: 'Shophouse kinh doanh tại Times City',
    address: 'Hai Bà Trưng, Hà Nội',
    city: 'Hà Nội',
    property_type: 'Cho thuê mặt bằng',
    bedrooms: 0,
    bathrooms: 2,
    price: 45000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 80,
    verified: true,
    package_type: 'standard',
    status: 'archived',
    posted_date: '2024-10-15',
    expiry_date: '2024-11-15',
    auto_repost: false,
    stats: {
      views: 892,
      contacts: 67,
      customers: 12,
    },
  },
  // Additional listings for better pagination testing
  // VIP Diamond - Active
  {
    id: '41934463',
    code: '41934463',
    title: 'Cho thuê penthouse Landmark 81, view sông Sài Gòn',
    description: 'Penthouse cao cấp nhất Sài Gòn',
    address: 'Bình Thạnh, TP.HCM',
    city: 'TP.HCM',
    property_type: 'Cho thuê căn hộ chung cư',
    bedrooms: 4,
    bathrooms: 4,
    price: 150000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 400,
    verified: true,
    package_type: 'vip_diamond',
    status: 'active',
    posted_date: '2024-12-20',
    expiry_date: '2025-02-20',
    auto_repost: true,
    rank: {
      page: 1,
      position: 2,
    },
    stats: {
      views: 3200,
      contacts: 280,
      customers: 45,
    },
  },
  // VIP Gold - Active
  {
    id: '41934464',
    code: '41934464',
    title: 'Cho thuê villa Thảo Điền, hồ bơi riêng, sân vườn',
    description: 'Villa sang trọng tại Thảo Điền',
    address: 'Quận 2, TP.HCM',
    city: 'TP.HCM',
    property_type: 'Cho thuê biệt thự',
    bedrooms: 6,
    bathrooms: 5,
    price: 120000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 500,
    verified: true,
    package_type: 'vip_gold',
    status: 'active',
    posted_date: '2024-12-18',
    expiry_date: '2025-02-18',
    auto_repost: true,
    stats: {
      views: 1890,
      contacts: 145,
      customers: 23,
    },
  },
  // VIP Silver - Pending
  {
    id: '41934465',
    code: '41934465',
    title: 'Cho thuê căn hộ Masteri Thảo Điền, 2PN, full nội thất',
    description: 'Căn hộ cao cấp Masteri Thảo Điền',
    address: 'Quận 2, TP.HCM',
    city: 'TP.HCM',
    property_type: 'Cho thuê căn hộ chung cư',
    bedrooms: 2,
    bathrooms: 2,
    price: 25000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 85,
    verified: true,
    package_type: 'vip_silver',
    status: 'pending',
    posted_date: '2025-01-02',
    expiry_date: '2025-03-02',
    auto_repost: false,
    stats: {
      views: 0,
      contacts: 0,
      customers: 0,
    },
  },
  // Standard - Active
  {
    id: '41934466',
    code: '41934466',
    title: 'Cho thuê nhà trọ Q.1, gần trung tâm, giá sinh viên',
    description: 'Nhà trọ tiện lợi gần trung tâm',
    address: 'Quận 1, TP.HCM',
    city: 'TP.HCM',
    property_type: 'Cho thuê phòng trọ',
    bedrooms: 1,
    bathrooms: 1,
    price: 6000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 20,
    verified: false,
    package_type: 'standard',
    status: 'active',
    posted_date: '2024-12-31',
    expiry_date: '2025-01-31',
    auto_repost: true,
    stats: {
      views: 156,
      contacts: 12,
      customers: 3,
    },
  },
  // Basic - Expired
  {
    id: '41934467',
    code: '41934467',
    title: 'Cho thuê văn phòng Q.3, giá rẻ, diện tích nhỏ',
    description: 'Văn phòng nhỏ phù hợp startup',
    address: 'Quận 3, TP.HCM',
    city: 'TP.HCM',
    property_type: 'Cho thuê văn phòng',
    bedrooms: 0,
    bathrooms: 1,
    price: 15000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 40,
    verified: false,
    package_type: 'basic',
    status: 'expired',
    posted_date: '2024-11-15',
    expiry_date: '2024-12-15',
    auto_repost: false,
    stats: {
      views: 234,
      contacts: 8,
      customers: 1,
    },
  },
  // VIP Diamond - Expiring
  {
    id: '41934468',
    code: '41934468',
    title: 'Cho thuê resort mini Đà Lạt, view núi đồi',
    description: 'Resort mini với view tuyệt đẹp',
    address: 'Đà Lạt, Lâm Đồng',
    city: 'Đà Lạt',
    property_type: 'Cho thuê biệt thự',
    bedrooms: 8,
    bathrooms: 6,
    price: 200000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 800,
    verified: true,
    package_type: 'vip_diamond',
    status: 'expiring',
    posted_date: '2024-11-10',
    expiry_date: '2025-01-08',
    auto_repost: true,
    stats: {
      views: 4500,
      contacts: 320,
      customers: 67,
    },
  },
  // VIP Gold - Review
  {
    id: '41934469',
    code: '41934469',
    title: 'Cho thuê khách sạn mini Vũng Tàu, gần biển',
    description: 'Khách sạn mini 15 phòng gần biển',
    address: 'Vũng Tàu, Bà Rịa - Vũng Tàu',
    city: 'Vũng Tàu',
    property_type: 'Cho thuê khách sạn',
    bedrooms: 15,
    bathrooms: 15,
    price: 80000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 600,
    verified: true,
    package_type: 'vip_gold',
    status: 'review',
    posted_date: '2025-01-01',
    expiry_date: '2025-03-01',
    auto_repost: false,
    stats: {
      views: 0,
      contacts: 0,
      customers: 0,
    },
  },
  // VIP Silver - Payment
  {
    id: '41934470',
    code: '41934470',
    title: 'Cho thuê condotel Nha Trang, view biển trực diện',
    description: 'Condotel cao cấp view biển Nha Trang',
    address: 'Nha Trang, Khánh Hòa',
    city: 'Nha Trang',
    property_type: 'Cho thuê condotel',
    bedrooms: 2,
    bathrooms: 2,
    price: 40000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 90,
    verified: true,
    package_type: 'vip_silver',
    status: 'payment',
    posted_date: '2025-01-03',
    expiry_date: '2025-03-03',
    auto_repost: false,
    stats: {
      views: 0,
      contacts: 0,
      customers: 0,
    },
  },
  // Standard - Rejected
  {
    id: '41934471',
    code: '41934471',
    title: 'Cho thuê homestay Sapa, view ruộng bậc thang',
    description: 'Homestay truyền thống với view đẹp',
    address: 'Sapa, Lào Cai',
    city: 'Sapa',
    property_type: 'Cho thuê homestay',
    bedrooms: 4,
    bathrooms: 3,
    price: 12000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 150,
    verified: false,
    package_type: 'standard',
    status: 'rejected',
    posted_date: '2024-12-28',
    expiry_date: '2025-02-28',
    auto_repost: false,
    stats: {
      views: 45,
      contacts: 2,
      customers: 0,
    },
  },
  // Basic - Archived
  {
    id: '41934472',
    code: '41934472',
    title: 'Cho thuê kho xưởng Bình Dương, gần KCN',
    description: 'Kho xưởng sản xuất gần khu công nghiệp',
    address: 'Thuận An, Bình Dương',
    city: 'Bình Dương',
    property_type: 'Cho thuê kho xưởng',
    bedrooms: 0,
    bathrooms: 2,
    price: 35000000,
    currency: 'VND',
    images: ['/images/default-image.jpg'],
    area: 1000,
    verified: true,
    package_type: 'basic',
    status: 'archived',
    posted_date: '2024-09-15',
    expiry_date: '2024-10-15',
    auto_repost: false,
    stats: {
      views: 567,
      contacts: 23,
      customers: 4,
    },
  },
]
